# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-26 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('author', models.CharField(max_length=100, unique=True)),
                ('narrator', models.CharField(max_length=100, unique=True)),
                ('duration', models.PositiveIntegerField()),
                ('uploadedTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Podcost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podcost_name', models.CharField(max_length=100, unique=True)),
                ('duration', models.PositiveIntegerField()),
                ('uploadedTime', models.DateTimeField()),
                ('host', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songName', models.CharField(max_length=100, unique=True)),
                ('duration', models.PositiveIntegerField()),
                ('uploadedTime', models.DateTimeField()),
            ],
        ),
    ]
